version: "3"

services:
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432"
    recipes_api:
        depends_on:
            - db
        build:
            context: ..
            dockerfile: local/Dockerfile
        volumes:
            - ../:/code
        ports:
            - "8000:8000"
        env_file:
            - ./.env

volumes:
    postgres_data:
