# Generated by Django 3.2.9 on 2021-11-12 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="ingredient's name", max_length=50, unique=True)),
                ('recipes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='recipes where the ingredient is used', max_length=50), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="recipe's name", max_length=50, unique=True)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text="recipe's ingredient", max_length=50), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
