# Generated by Django 3.2.9 on 2021-11-12 16:24

from django.db import migrations
from apps.recipes.models import (Recipe, Ingredient)



def load_data(apps, schema_editor):
    """..."""

    # Recipe creation
    Recipe(name="peanut butter and jelly sandwich", ingredients=["peanut butter", "jelly", "bread"]).save()
    Recipe(name="buckeyes", ingredients=["chocolate", "peanut butter", "sugar"]).save()
    Recipe(name="hawaiian pizza", ingredients=["cheese", "pizza dough", "tomato sauce", "pineapple", "bacon"]).save()
    Recipe(name="hot chocolate", ingredients=["milk", "chocolate", "sugar"]).save()
    Recipe(name="grilled cheese sandwich", ingredients=["cheese", "bread"]).save()

    #Ingredient creation
    Ingredient(name="peanut butter", recipes=["peanut butter and jelly sandwich", "buckeyes"]).save()
    Ingredient(name="jelly", recipes=["peanut butter and jelly sandwich"]).save()
    Ingredient(name="bread", recipes=["peanut butter and jelly sandwich", "grilled cheese sandwich"]).save()
    Ingredient(name="chocolate", recipes=["buckeyes", "hot chocolate"]).save()
    Ingredient(name="sugar", recipes=["buckeyes", "hot chocolate"]).save()
    Ingredient(name="cheese", recipes=["hawaiian pizza", "grilled cheese sandwich"]).save()
    Ingredient(name="pizza dough", recipes=["hawaiian pizza"]).save()
    Ingredient(name="tomato sauce", recipes=["hawaiian pizza"]).save()
    Ingredient(name="pineapple", recipes=["hawaiian pizza"]).save()
    Ingredient(name="bacon", recipes=["hawaiian pizza"]).save()
    Ingredient(name="milk", recipes=["hot chocolate"]).save()



class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]

